apiVersion: 1

datasources:
  - name: vigilex-postgres
    uid: vigilex-postgres-uid
    type: postgres
    url: postgres:5432
    database: vigilex
    user: vigilex
    secureJsonData:
      password: '${GF_POSTGRES_PASSWORD}'
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: false
    editable: true
