apiVersion: 1

datasources:
  - name: vigilex-postgres
    uid: vigilex-postgres-uid
    type: postgres
    url: postgres:5432
    user: vigilex_readonly
    secureJsonData:
      password: "$GF_POSTGRES_PASSWORD"
    jsonData:
      database: vigilex
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isD